import {
  type Cyclone,
  type CycloneAlert,
  type AIPrediction,
  CycloneCategory,
  CycloneStatus,
  AlertSeverity,
  BasinCode,
} from "@/types/cyclone";

// ─── Helper: generate timestamps relative to now ─────────────────────────────

function hoursAgo(h: number): string {
  return new Date(Date.now() - h * 3600_000).toISOString();
}

function hoursFromNow(h: number): string {
  return new Date(Date.now() + h * 3600_000).toISOString();
}

// ─── Mock Cyclones ───────────────────────────────────────────────────────────

export const MOCK_CYCLONES: Cyclone[] = [
  {
    id: "WP142025",
    name: "TYPHOON HAILONG",
    basin: BasinCode.WP,
    season: 2025,
    status: CycloneStatus.ACTIVE,
    currentPosition: {
      latitude: 18.4,
      longitude: 132.6,
      timestamp: hoursAgo(0),
      windSpeed: 125,
      pressure: 940,
      category: CycloneCategory.C4,
      movementSpeed: 12,
      movementDirection: 315,
    },
    track: [
      { latitude: 12.1, longitude: 142.3, timestamp: hoursAgo(72), windSpeed: 35, pressure: 1002, category: CycloneCategory.TS },
      { latitude: 13.0, longitude: 141.0, timestamp: hoursAgo(60), windSpeed: 50, pressure: 992, category: CycloneCategory.TS },
      { latitude: 13.8, longitude: 139.8, timestamp: hoursAgo(48), windSpeed: 65, pressure: 980, category: CycloneCategory.C1 },
      { latitude: 14.7, longitude: 138.5, timestamp: hoursAgo(36), windSpeed: 85, pressure: 965, category: CycloneCategory.C2 },
      { latitude: 15.8, longitude: 137.0, timestamp: hoursAgo(24), windSpeed: 100, pressure: 955, category: CycloneCategory.C3 },
      { latitude: 17.0, longitude: 135.2, timestamp: hoursAgo(12), windSpeed: 115, pressure: 945, category: CycloneCategory.C4 },
      { latitude: 18.4, longitude: 132.6, timestamp: hoursAgo(0), windSpeed: 125, pressure: 940, category: CycloneCategory.C4 },
    ],
    forecast: [
      { latitude: 19.5, longitude: 130.8, forecastHour: 12, timestamp: hoursFromNow(12), windSpeed: 130, pressure: 935, category: CycloneCategory.C4, confidence: 0.92 },
      { latitude: 20.8, longitude: 128.5, forecastHour: 24, timestamp: hoursFromNow(24), windSpeed: 135, pressure: 930, category: CycloneCategory.C4, confidence: 0.87 },
      { latitude: 22.5, longitude: 126.0, forecastHour: 48, timestamp: hoursFromNow(48), windSpeed: 125, pressure: 940, category: CycloneCategory.C4, confidence: 0.78 },
      { latitude: 25.0, longitude: 124.0, forecastHour: 72, timestamp: hoursFromNow(72), windSpeed: 110, pressure: 950, category: CycloneCategory.C3, confidence: 0.65 },
      { latitude: 28.5, longitude: 123.5, forecastHour: 96, timestamp: hoursFromNow(96), windSpeed: 90, pressure: 960, category: CycloneCategory.C2, confidence: 0.52 },
      { latitude: 32.0, longitude: 125.0, forecastHour: 120, timestamp: hoursFromNow(120), windSpeed: 75, pressure: 972, category: CycloneCategory.C1, confidence: 0.40 },
    ],
    forecastCone: {
      centerLine: [
        { latitude: 19.5, longitude: 130.8, forecastHour: 12, timestamp: hoursFromNow(12), windSpeed: 130, pressure: 935, category: CycloneCategory.C4, confidence: 0.92 },
        { latitude: 22.5, longitude: 126.0, forecastHour: 48, timestamp: hoursFromNow(48), windSpeed: 125, pressure: 940, category: CycloneCategory.C4, confidence: 0.78 },
        { latitude: 28.5, longitude: 123.5, forecastHour: 96, timestamp: hoursFromNow(96), windSpeed: 90, pressure: 960, category: CycloneCategory.C2, confidence: 0.52 },
      ],
      conePolygon: [
        { latitude: 18.4, longitude: 132.6, forecastHour: 0 },
        { latitude: 19.0, longitude: 131.5, forecastHour: 12 },
        { latitude: 21.5, longitude: 127.5, forecastHour: 48 },
        { latitude: 26.5, longitude: 125.5, forecastHour: 96 },
        { latitude: 33.5, longitude: 127.0, forecastHour: 120 },
        { latitude: 31.0, longitude: 123.0, forecastHour: 120 },
        { latitude: 30.0, longitude: 121.5, forecastHour: 96 },
        { latitude: 24.0, longitude: 124.0, forecastHour: 48 },
        { latitude: 20.0, longitude: 129.5, forecastHour: 12 },
        { latitude: 18.4, longitude: 132.6, forecastHour: 0 },
      ],
      generatedAt: hoursAgo(0),
    },
    windData: {
      maxSustainedWind: 125,
      gustSpeed: 155,
      windRadii34kt: { ne: 200, se: 180, sw: 150, nw: 170 },
      windRadii50kt: { ne: 100, se: 90, sw: 80, nw: 85 },
      windRadii64kt: { ne: 50, se: 45, sw: 35, nw: 40 },
      timestamp: hoursAgo(0),
    },
    pressureData: {
      centralPressure: 940,
      outerPressure: 1010,
      pressureTendency: -2.5,
      timestamp: hoursAgo(0),
    },
    formationDate: hoursAgo(96),
    lastUpdated: hoursAgo(0),
    advisoryNumber: "Advisory 22",
    source: "JTWC",
  },
  {
    id: "AL062025",
    name: "HURRICANE MARIA",
    basin: BasinCode.NA,
    season: 2025,
    status: CycloneStatus.ACTIVE,
    currentPosition: {
      latitude: 22.3,
      longitude: -65.8,
      timestamp: hoursAgo(0),
      windSpeed: 95,
      pressure: 960,
      category: CycloneCategory.C2,
      movementSpeed: 10,
      movementDirection: 330,
    },
    track: [
      { latitude: 16.5, longitude: -56.2, timestamp: hoursAgo(72), windSpeed: 40, pressure: 1000, category: CycloneCategory.TS },
      { latitude: 17.2, longitude: -58.0, timestamp: hoursAgo(60), windSpeed: 55, pressure: 990, category: CycloneCategory.TS },
      { latitude: 18.0, longitude: -59.5, timestamp: hoursAgo(48), windSpeed: 70, pressure: 978, category: CycloneCategory.C1 },
      { latitude: 19.0, longitude: -61.0, timestamp: hoursAgo(36), windSpeed: 80, pressure: 970, category: CycloneCategory.C1 },
      { latitude: 20.2, longitude: -62.8, timestamp: hoursAgo(24), windSpeed: 85, pressure: 965, category: CycloneCategory.C2 },
      { latitude: 21.3, longitude: -64.5, timestamp: hoursAgo(12), windSpeed: 90, pressure: 962, category: CycloneCategory.C2 },
      { latitude: 22.3, longitude: -65.8, timestamp: hoursAgo(0), windSpeed: 95, pressure: 960, category: CycloneCategory.C2 },
    ],
    forecast: [
      { latitude: 23.5, longitude: -67.0, forecastHour: 12, timestamp: hoursFromNow(12), windSpeed: 100, pressure: 955, category: CycloneCategory.C3, confidence: 0.88 },
      { latitude: 25.0, longitude: -68.5, forecastHour: 24, timestamp: hoursFromNow(24), windSpeed: 105, pressure: 950, category: CycloneCategory.C3, confidence: 0.82 },
      { latitude: 27.5, longitude: -70.0, forecastHour: 48, timestamp: hoursFromNow(48), windSpeed: 95, pressure: 958, category: CycloneCategory.C2, confidence: 0.72 },
      { latitude: 31.0, longitude: -71.5, forecastHour: 72, timestamp: hoursFromNow(72), windSpeed: 80, pressure: 968, category: CycloneCategory.C1, confidence: 0.60 },
      { latitude: 35.0, longitude: -70.0, forecastHour: 96, timestamp: hoursFromNow(96), windSpeed: 65, pressure: 980, category: CycloneCategory.C1, confidence: 0.48 },
    ],
    forecastCone: {
      centerLine: [
        { latitude: 23.5, longitude: -67.0, forecastHour: 12, timestamp: hoursFromNow(12), windSpeed: 100, pressure: 955, category: CycloneCategory.C3, confidence: 0.88 },
        { latitude: 27.5, longitude: -70.0, forecastHour: 48, timestamp: hoursFromNow(48), windSpeed: 95, pressure: 958, category: CycloneCategory.C2, confidence: 0.72 },
        { latitude: 35.0, longitude: -70.0, forecastHour: 96, timestamp: hoursFromNow(96), windSpeed: 65, pressure: 980, category: CycloneCategory.C1, confidence: 0.48 },
      ],
      conePolygon: [
        { latitude: 22.3, longitude: -65.8, forecastHour: 0 },
        { latitude: 23.0, longitude: -66.0, forecastHour: 12 },
        { latitude: 26.0, longitude: -68.5, forecastHour: 48 },
        { latitude: 33.0, longitude: -68.0, forecastHour: 96 },
        { latitude: 37.0, longitude: -72.0, forecastHour: 96 },
        { latitude: 29.0, longitude: -72.0, forecastHour: 48 },
        { latitude: 24.0, longitude: -68.5, forecastHour: 12 },
        { latitude: 22.3, longitude: -65.8, forecastHour: 0 },
      ],
      generatedAt: hoursAgo(0),
    },
    windData: {
      maxSustainedWind: 95,
      gustSpeed: 115,
      windRadii34kt: { ne: 180, se: 160, sw: 120, nw: 140 },
      windRadii50kt: { ne: 80, se: 70, sw: 50, nw: 60 },
      windRadii64kt: { ne: 40, se: 35, sw: 25, nw: 30 },
      timestamp: hoursAgo(0),
    },
    pressureData: {
      centralPressure: 960,
      outerPressure: 1012,
      pressureTendency: -1.8,
      timestamp: hoursAgo(0),
    },
    formationDate: hoursAgo(120),
    lastUpdated: hoursAgo(0),
    advisoryNumber: "Advisory 18",
    source: "NHC",
  },
  {
    id: "NI032025",
    name: "CYCLONE AMPHAN",
    basin: BasinCode.NI,
    season: 2025,
    status: CycloneStatus.ACTIVE,
    currentPosition: {
      latitude: 15.6,
      longitude: 87.2,
      timestamp: hoursAgo(0),
      windSpeed: 75,
      pressure: 972,
      category: CycloneCategory.C1,
      movementSpeed: 8,
      movementDirection: 350,
    },
    track: [
      { latitude: 10.5, longitude: 88.5, timestamp: hoursAgo(48), windSpeed: 35, pressure: 1000, category: CycloneCategory.TS },
      { latitude: 11.5, longitude: 88.2, timestamp: hoursAgo(36), windSpeed: 50, pressure: 990, category: CycloneCategory.TS },
      { latitude: 12.8, longitude: 87.9, timestamp: hoursAgo(24), windSpeed: 60, pressure: 982, category: CycloneCategory.TS },
      { latitude: 14.0, longitude: 87.5, timestamp: hoursAgo(12), windSpeed: 70, pressure: 975, category: CycloneCategory.C1 },
      { latitude: 15.6, longitude: 87.2, timestamp: hoursAgo(0), windSpeed: 75, pressure: 972, category: CycloneCategory.C1 },
    ],
    forecast: [
      { latitude: 17.0, longitude: 87.0, forecastHour: 12, timestamp: hoursFromNow(12), windSpeed: 85, pressure: 965, category: CycloneCategory.C2, confidence: 0.85 },
      { latitude: 18.5, longitude: 86.8, forecastHour: 24, timestamp: hoursFromNow(24), windSpeed: 90, pressure: 960, category: CycloneCategory.C2, confidence: 0.78 },
      { latitude: 20.5, longitude: 87.0, forecastHour: 48, timestamp: hoursFromNow(48), windSpeed: 80, pressure: 968, category: CycloneCategory.C1, confidence: 0.65 },
      { latitude: 22.0, longitude: 88.0, forecastHour: 72, timestamp: hoursFromNow(72), windSpeed: 55, pressure: 985, category: CycloneCategory.TS, confidence: 0.50 },
    ],
    forecastCone: null,
    windData: {
      maxSustainedWind: 75,
      gustSpeed: 95,
      windRadii34kt: { ne: 130, se: 120, sw: 100, nw: 110 },
      windRadii50kt: { ne: 60, se: 50, sw: 40, nw: 45 },
      windRadii64kt: { ne: 25, se: 20, sw: 15, nw: 18 },
      timestamp: hoursAgo(0),
    },
    pressureData: {
      centralPressure: 972,
      outerPressure: 1008,
      pressureTendency: -3.0,
      timestamp: hoursAgo(0),
    },
    formationDate: hoursAgo(72),
    lastUpdated: hoursAgo(0),
    advisoryNumber: "Advisory 10",
    source: "IMD",
  },
  {
    id: "EP092025",
    name: "TROPICAL STORM NORA",
    basin: BasinCode.EP,
    season: 2025,
    status: CycloneStatus.ACTIVE,
    currentPosition: {
      latitude: 16.2,
      longitude: -108.5,
      timestamp: hoursAgo(0),
      windSpeed: 55,
      pressure: 992,
      category: CycloneCategory.TS,
      movementSpeed: 14,
      movementDirection: 300,
    },
    track: [
      { latitude: 13.5, longitude: -104.0, timestamp: hoursAgo(36), windSpeed: 30, pressure: 1005, category: CycloneCategory.TD },
      { latitude: 14.2, longitude: -105.5, timestamp: hoursAgo(24), windSpeed: 40, pressure: 1000, category: CycloneCategory.TS },
      { latitude: 15.1, longitude: -107.0, timestamp: hoursAgo(12), windSpeed: 50, pressure: 995, category: CycloneCategory.TS },
      { latitude: 16.2, longitude: -108.5, timestamp: hoursAgo(0), windSpeed: 55, pressure: 992, category: CycloneCategory.TS },
    ],
    forecast: [
      { latitude: 17.2, longitude: -110.0, forecastHour: 12, timestamp: hoursFromNow(12), windSpeed: 60, pressure: 988, category: CycloneCategory.TS, confidence: 0.90 },
      { latitude: 18.5, longitude: -112.0, forecastHour: 24, timestamp: hoursFromNow(24), windSpeed: 65, pressure: 980, category: CycloneCategory.C1, confidence: 0.80 },
      { latitude: 20.0, longitude: -114.5, forecastHour: 48, timestamp: hoursFromNow(48), windSpeed: 55, pressure: 990, category: CycloneCategory.TS, confidence: 0.65 },
      { latitude: 22.0, longitude: -117.0, forecastHour: 72, timestamp: hoursFromNow(72), windSpeed: 40, pressure: 1000, category: CycloneCategory.TS, confidence: 0.50 },
    ],
    forecastCone: null,
    windData: {
      maxSustainedWind: 55,
      gustSpeed: 70,
      windRadii34kt: { ne: 100, se: 80, sw: 70, nw: 90 },
      windRadii50kt: { ne: 40, se: 30, sw: 25, nw: 35 },
      windRadii64kt: { ne: 0, se: 0, sw: 0, nw: 0 },
      timestamp: hoursAgo(0),
    },
    pressureData: {
      centralPressure: 992,
      outerPressure: 1010,
      pressureTendency: -1.2,
      timestamp: hoursAgo(0),
    },
    formationDate: hoursAgo(60),
    lastUpdated: hoursAgo(0),
    advisoryNumber: "Advisory 7",
    source: "NHC",
  },
];

// ─── Mock Alerts ─────────────────────────────────────────────────────────────

export const MOCK_ALERTS: CycloneAlert[] = [
  {
    id: "alert-001",
    cycloneId: "WP142025",
    cycloneName: "TYPHOON HAILONG",
    severity: AlertSeverity.EMERGENCY,
    title: "Super Typhoon Warning — Western Pacific",
    message:
      "Typhoon Hailong has intensified to Category 4 with sustained winds of 125 kt. Extreme danger for southern Japan and Okinawa. Immediate evacuation recommended for coastal areas.",
    affectedAreas: ["Okinawa", "Southern Japan", "Taiwan Strait", "Northern Philippines"],
    issuedAt: hoursAgo(2),
    expiresAt: hoursFromNow(24),
    source: "JTWC",
  },
  {
    id: "alert-002",
    cycloneId: "AL062025",
    cycloneName: "HURRICANE MARIA",
    severity: AlertSeverity.WARNING,
    title: "Hurricane Warning — Eastern Caribbean",
    message:
      "Hurricane Maria is expected to strengthen to Category 3 within 24 hours. Hurricane warnings are in effect for Puerto Rico and the US Virgin Islands.",
    affectedAreas: ["Puerto Rico", "US Virgin Islands", "Leeward Islands", "Turks and Caicos"],
    issuedAt: hoursAgo(4),
    expiresAt: hoursFromNow(48),
    source: "NHC",
  },
  {
    id: "alert-003",
    cycloneId: "NI032025",
    cycloneName: "CYCLONE AMPHAN",
    severity: AlertSeverity.WATCH,
    title: "Cyclone Watch — Bay of Bengal",
    message:
      "Cyclone Amphan is expected to intensify over the Bay of Bengal. Cyclone watch issued for Odisha and West Bengal coasts. Fishermen advised not to venture into the sea.",
    affectedAreas: ["Odisha Coast", "West Bengal Coast", "Andhra Pradesh Coast"],
    issuedAt: hoursAgo(6),
    expiresAt: hoursFromNow(72),
    source: "IMD",
  },
  {
    id: "alert-004",
    cycloneId: "EP092025",
    cycloneName: "TROPICAL STORM NORA",
    severity: AlertSeverity.INFORMATION,
    title: "Tropical Storm Advisory — Eastern Pacific",
    message:
      "Tropical Storm Nora continues to move northwest. No immediate threat to land, but mariners should exercise caution in the Eastern Pacific.",
    affectedAreas: ["Eastern Pacific shipping lanes"],
    issuedAt: hoursAgo(8),
    expiresAt: hoursFromNow(24),
    source: "NHC",
  },
];

// ─── Mock AI Predictions ─────────────────────────────────────────────────────

export const MOCK_AI_PREDICTIONS: AIPrediction[] = [
  {
    id: "pred-001",
    cycloneId: "WP142025",
    model: {
      modelId: "cyclone-transformer-v2",
      modelVersion: "2.1.0",
      modelName: "CycloneNet Transformer",
      lastTrained: hoursAgo(168),
      accuracy: 0.87,
    },
    predictedTrack: [
      { latitude: 19.8, longitude: 130.2, forecastHour: 12, timestamp: hoursFromNow(12), predictedWindSpeed: 132, predictedPressure: 933, predictedCategory: CycloneCategory.C4, confidence: 0.91, upperBoundWind: 145, lowerBoundWind: 118 },
      { latitude: 21.5, longitude: 127.5, forecastHour: 24, timestamp: hoursFromNow(24), predictedWindSpeed: 138, predictedPressure: 928, predictedCategory: CycloneCategory.C5, confidence: 0.85, upperBoundWind: 155, lowerBoundWind: 120 },
      { latitude: 24.0, longitude: 125.0, forecastHour: 48, timestamp: hoursFromNow(48), predictedWindSpeed: 128, predictedPressure: 935, predictedCategory: CycloneCategory.C4, confidence: 0.75, upperBoundWind: 148, lowerBoundWind: 108 },
      { latitude: 27.5, longitude: 123.0, forecastHour: 72, timestamp: hoursFromNow(72), predictedWindSpeed: 105, predictedPressure: 952, predictedCategory: CycloneCategory.C3, confidence: 0.62, upperBoundWind: 125, lowerBoundWind: 85 },
      { latitude: 31.5, longitude: 124.0, forecastHour: 96, timestamp: hoursFromNow(96), predictedWindSpeed: 82, predictedPressure: 968, predictedCategory: CycloneCategory.C1, confidence: 0.48, upperBoundWind: 100, lowerBoundWind: 65 },
    ],
    predictedLandfall: { latitude: 29.5, longitude: 123.5 },
    predictedLandfallTime: hoursFromNow(84),
    predictedPeakIntensity: 140,
    predictedPeakCategory: CycloneCategory.C5,
    overallConfidence: 0.78,
    generatedAt: hoursAgo(1),
  },
  {
    id: "pred-002",
    cycloneId: "AL062025",
    model: {
      modelId: "cyclone-transformer-v2",
      modelVersion: "2.1.0",
      modelName: "CycloneNet Transformer",
      lastTrained: hoursAgo(168),
      accuracy: 0.87,
    },
    predictedTrack: [
      { latitude: 23.8, longitude: -66.5, forecastHour: 12, timestamp: hoursFromNow(12), predictedWindSpeed: 105, predictedPressure: 950, predictedCategory: CycloneCategory.C3, confidence: 0.88, upperBoundWind: 118, lowerBoundWind: 92 },
      { latitude: 26.0, longitude: -68.0, forecastHour: 24, timestamp: hoursFromNow(24), predictedWindSpeed: 110, predictedPressure: 945, predictedCategory: CycloneCategory.C3, confidence: 0.80, upperBoundWind: 125, lowerBoundWind: 95 },
      { latitude: 29.0, longitude: -70.5, forecastHour: 48, timestamp: hoursFromNow(48), predictedWindSpeed: 100, predictedPressure: 952, predictedCategory: CycloneCategory.C3, confidence: 0.68, upperBoundWind: 118, lowerBoundWind: 82 },
    ],
    predictedLandfall: null,
    predictedLandfallTime: null,
    predictedPeakIntensity: 115,
    predictedPeakCategory: CycloneCategory.C4,
    overallConfidence: 0.79,
    generatedAt: hoursAgo(1),
  },
];
